# docker-compose.yml

version: '3.8'

services:
  web:
    build: .
    env_file:
      - .env
    ports:
      - "5000:5000"
    restart: on-failure
    deploy:
      restart_policy:
        condition: on-failure
        max_attempts: 5

